# Generated by Django 2.1.1 on 2018-09-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='apk',
            field=models.FileField(default='apk/test.apk', upload_to='apk', verbose_name='APK File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appversion',
            name='whats_new',
            field=models.TextField(blank=True, null=True, verbose_name="What's New"),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
