# Generated by Django 2.1.1 on 2018-09-06 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180905_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='apk',
            field=models.FileField(upload_to='apk', validators=[django.core.validators.FileExtensionValidator(['apk'])], verbose_name='APK File'),
        ),
    ]
