# Generated by Django 2.1 on 2018-08-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.MobileApp'),
        ),
    ]
