# Generated by Django 2.1 on 2018-08-31 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20180829_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('*[a-zA-Z0-9\\.]')]),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='tags',
            field=models.ManyToManyField(to='management.Tag'),
        ),
    ]
