# Generated by Django 2.1.1 on 2018-09-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='active_status',
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='active_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=10),
        ),
    ]
