# Generated by Django 2.1.1 on 2018-09-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20180909_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileapp',
            old_name='active_status',
            new_name='is_active',
        ),
    ]
