# Generated by Django 2.1.1 on 2018-09-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20180903_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapp',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
