# Generated by Django 2.1.1 on 2018-09-11 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20180909_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='approve_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved Time'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='mobile_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.MobileApp', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9\\.]*')], verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MobileApp', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approve_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedComments', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdComments', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='evluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Evaluation', verbose_name='Evaluation'),
        ),
        migrations.AlterField(
            model_name='download',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.MobileApp', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='download',
            name='download_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Download At'),
        ),
        migrations.AlterField(
            model_name='download',
            name='mobile',
            field=models.CharField(max_length=100, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='download',
            name='os',
            field=models.CharField(max_length=100, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MobileApp', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='approve_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedEvaluations', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdEvaluations', to=settings.AUTH_USER_MODEL, verbose_name='Comment By'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment At'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='rate',
            field=models.PositiveSmallIntegerField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='avg_rate',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Average Rate'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='comment_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Comment Count'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='download_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='tags',
            field=models.ManyToManyField(to='management.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Time'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
    ]
