# Generated by Django 2.1.1 on 2018-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20180911_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='icon',
            field=models.ImageField(default='icon_1.png', upload_to='icons'),
            preserve_default=False,
        ),
    ]
