# Generated by Django 2.1.1 on 2018-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_mobileapp_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='banners')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
            ],
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='avg_rate',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, null=True, verbose_name='Average Rate'),
        ),
    ]
