# Generated by Django 2.1.1 on 2018-09-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20180916_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='android_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supported Android Version'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Translator'),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners', verbose_name='Banner Image'),
        ),
    ]
