# Generated by Django 2.1.1 on 2018-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20180919_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapp',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Comment Count'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='download_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Download Count'),
        ),
    ]
