# Generated by Django 2.1.1 on 2018-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20180924_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
