# Generated by Django 2.1.1 on 2018-09-27 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20180924_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='apk', validators=[django.core.validators.FileExtensionValidator(['apk', 'xapk'])], verbose_name='APK File')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='apk',
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='apkfile',
            name='app_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apk', to='management.AppVersion'),
        ),
    ]
