# Generated by Django 2.1.1 on 2018-10-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20180927_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'ordering': ['-upload_date'], 'permissions': (('can_approve_app', 'Can approve newly uploaded app'),)},
        ),
        migrations.AlterField(
            model_name='appversion',
            name='mobile_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='management.MobileApp', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, verbose_name='Gender'),
        ),
    ]
