# Generated by Django 2.1.2 on 2018-10-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_appversion_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'ordering': ('order',), 'permissions': (('can_approve_app', 'Can approve newly uploaded app'),)},
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
