# Generated by Django 2.1.2 on 2018-10-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20181007_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Upload Time'),
        ),
    ]
