# Generated by Django 2.1.2 on 2018-10-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_auto_20181009_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('mobile_app', 'version_number')},
        ),
    ]
