# Generated by Django 2.1.2 on 2018-10-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20181018_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileapp',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
