# Generated by Django 2.1.2 on 2018-10-28 11:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('management', '0025_auto_20181028_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
