# Generated by Django 2.1.2 on 2018-10-30 07:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_mobileapp_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='app',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='evluation',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='app',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
