# Generated by Django 2.1.2 on 2018-10-30 08:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0027_auto_20181030_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Upload Time')),
                ('approve_status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='Approved Time')),
                ('download_count', models.PositiveIntegerField(default=0, null=True, verbose_name='Download Count')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')])),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
        ),
    ]
