# Generated by Django 2.1.2 on 2018-10-30 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_pdfdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdoc',
            name='pdf_file',
            field=models.FileField(default='pdf/test.pdf', upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF File'),
            preserve_default=False,
        ),
    ]
