# Generated by Django 2.1.2 on 2018-10-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20181031_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdoc',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark'),
        ),
    ]
