# Generated by Django 2.1.2 on 2018-10-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_pdfdoc_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdoc',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='management.PDFDoc'),
        ),
    ]
