# Generated by Django 2.1.2 on 2018-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20181031_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdoc',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
