# Generated by Django 2.1.2 on 2018-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20181031_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdoc',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='pdfdoc',
            name='publish_year',
            field=models.DateField(blank=True, null=True, verbose_name='Publish Year'),
        ),
    ]
