# Generated by Django 2.1.2 on 2018-11-09 13:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0034_auto_20181031_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspiredVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Upload Time')),
                ('approve_status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='Approved Time')),
                ('download_count', models.PositiveIntegerField(default=0, null=True, verbose_name='Download Count')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')])),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Upload Time')),
                ('approve_status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=10, verbose_name='Approve Status')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='Approved Time')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')])),
                ('video_count', models.SmallIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
        ),
        migrations.AddField(
            model_name='inspiredvideo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.VideoAlbum', verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='inspiredvideo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='inspiredvideo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='inspiredvideo',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
