# Generated by Django 2.1.2 on 2018-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_auto_20181109_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspiredvideo',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AddField(
            model_name='inspiredvideo',
            name='screenshot',
            field=models.FilePathField(default=None, path='pictures/inspired_video/screenshot', verbose_name='screenshot'),
            preserve_default=False,
        ),
    ]
