# Generated by Django 2.1.2 on 2018-11-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_auto_20181111_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'get_latest_by': 'created_time', 'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='video',
            name='upyun_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
