# Generated by Django 2.1.2 on 2018-11-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_auto_20181122_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoalbum',
            name='video_count',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='image',
            name='upyun_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspiredvideo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_videos', to='management.VideoAlbum', verbose_name='Album'),
        ),
    ]
