# Generated by Django 2.1.2 on 2018-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_auto_20181125_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, max_length=150, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='videos'),
        ),
    ]
