# Generated by Django 2.1.2 on 2018-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_auto_20181125_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, max_length=150, upload_to='pictures'),
        ),
    ]
