# Generated by Django 2.1.2 on 2018-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_auto_20181126_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='pictures'),
        ),
    ]
