# Generated by Django 2.1.2 on 2018-12-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_auto_20181206_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoalbum',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
